### PR TITLE
Add some benchmarks

### PR DESCRIPTION
**Pull request by marcoow**
The benchmarks are rather naive for now but should actually be good enough for now to give us some idea for whether we're unreasonably slow (which doesn't seem to be the case).

Run the benchmarks at http://localhost:4200/benchmarks

### CODE REVIEW

**Comment by daliwali** [comment]
I ran the benchmarks locally, not bad. There is some overhead vs composable helpers but it's not that much.

Should there be a control variable, such as without using any addons?

**Comment by marcoow** [comment]
> There is some overhead vs composable helpers but it's not that much.

That would actually not be expected. There will be some overhead compared to regular CPs (first 2 buttons) but this should generally be on par with composable-helpers as it's more or less the same thing. I was also not seeing overhead really - maybe we should add an option for running the benchmarks x times to make sure we're seeing comparable numbers.

> Should there be a control variable, such as without using any addons?

Sure we could add another case for a CP based solution without classy-computed. All helper based solutions would actually look just like the code that's in composable-helpers - therefore, it's probably not worth it adding a variant with helpers that does not use composable-helpers.

**Comment by daliwali** [comment]
>Sure we could add another case for a CP based solution without classy-computed. All helper based solutions would actually look just like the code that's in composable-helpers - therefore, it's probably not worth it adding a variant with helpers that does not use composable-helpers.

The issue is that you are comparing one addon to another addon, without comparing it to *no addon*. I am suggesting that there should be a case for just using Ember to get a better picture of how it performs.

**Comment by marcoow** [comment]
> The issue is that you are comparing one addon to another addon, without comparing it to no addon. I am suggesting that there should be a case for just using Ember to get a better picture of how it performs. And maybe vanilla JS as a baseline :trollface:

The point is that when implementing a helper solution without ember-composable-helpers it will be the same code that's in ember-composable-helpers. I think a pure-Ember solution makes sense for comparison as it would actually work a bit different to the way ember-classy-computed works.

**Comment by marcoow** [comment]
> Had a quick look at the results and it seems that classy-computed does have a bit of overhead, but it seems to be in an acceptable range.

To be clear: we'd expect some overhead for the first benchmark (regular CP vs. class based CP) but we expect performance to be on par with class based helpers. If that's not the case we should investigate that as it might indicate room for improvements.

**Comment by Turbo87** [comment]
I just ran the benchmarks again and noticed that the times were varying a lot. I guess that this may be related to the JIT warming up or some stuff like that. tl;dr the times were not that different at all between all the implementations.

**Comment by marcoow** [comment]
@daliwali, @Turbo87: I added another implementation version using native Ember properties (which is actually pretty similar to the ember-class-computed version with the difference that it doesn't use an observer) and changed it so that each benchmark is run 10 times for more stable numbers.

My observations show that all of the 3 versions are pretty much on par performance wise.

**Pull request merged**
